### ISSUE TITLE
npm install fails if working folder has spaces in it

### ISSUE THREAD

**Issue by AxelTerizaki** [FocaBot/ffmpeg-downloader#1]
Hello.

I'm working on a project using your ffmpeg-downloader, and there is actually a little bug I discovered when trying to npm install on a windows platform : if you launch npm install from within a path containing spaces, it fails.

Maybe protecting the paths in the install script might resolve this ?

Thanks in advance :)

**Comment by TheBITLINK** [comment]
Should work fine now
